### ISSUE TITLE
"Campaign" typo in hint for Campaign ID field.

### ISSUE THREAD

**Issue by caffinito** [amitvc/perftool#11]
In v1.1, in the Offer Setup module, in the field where the user would type the Campaign ID number, there is a "hint" in gray as to what the user would enter in this field.

Campaign is misspelled as Campaing.  See screen shot.
![campaignspelling](https://cloud.githubusercontent.com/assets/13544244/9211886/edba1f64-4052-11e5-8cf2-3d27f7dbb973.jpg)

**Comment by amitvc** [comment]
Fixed
